variables:
  ST_VERSION: 0.14.36
  REGISTRY_HOST: registry.monach.us
  TEST_IMAGE: $REGISTRY_HOST/$CI_PROJECT_PATH:$CI_BUILD_REF_NAME
  RELEASE_IMAGE: $REGISTRY_HOST/$CI_PROJECT_PATH
  DOCKER_IMAGE: monachus/$CI_PROJECT_NAME
  
stages:
  - build
  - release

before_script:
  - docker info
  - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN $REGISTRY_HOST

build:
  stage: build
  script:
    - docker build --pull -t $TEST_IMAGE .
    - docker push $TEST_IMAGE

release:
  stage: release
  script:
    - docker pull $TEST_IMAGE
    - docker tag $TEST_IMAGE $RELEASE_IMAGE:$ST_VERSION
    - docker tag $TEST_IMAGE $RELEASE_IMAGE:latest
    - docker push $RELEASE_IMAGE:$ST_VERSION
    - docker push $RELEASE_IMAGE:latest
  only:
    - master

push_to_docker_hub:
  stage: release
  script:
    - docker login -u $HUB_USERNAME -p $HUB_PASSWORD
    - docker tag $RELEASE_IMAGE:$ST_VERSION $DOCKER_IMAGE:$ST_VERSION
    - docker tag $RELEASE_IMAGE:$ST_VERSION $DOCKER_IMAGE:latest
    - docker push $DOCKER_IMAGE:$ST_VERSION
    - docker push $DOCKER_IMAGE:latest
  only:
    - master
